# Enables logging of Mongo mapping events
logging.level.org.springframework=INFO
logging.level.eu.europa.eu.esig=DEBUG
logging.level.org.springframework.boot.actuate.endpoint.web=DEBUG

management.endpoints.access.default=unrestricted
spring.web.error.include-stacktrace=ALWAYS
server.port=8080
spring.webflux.static-path-pattern=/public/**
spring.webflux.webjars-path-pattern=/webjars/**
spring.messages.basename=i18n/messages

# cors
cors.origins=*
cors.originPatterns=*
cors.methods=*
cors.headers=*
cors.credentials=false
cors.maxAge=3600

# Trust Sources
trust-sources[0].type=KeyStore
trust-sources[0].verification-context=PID
trust-sources[0].key-store.location=classpath:lotl.jks
trust-sources[0].key-store.type=JKS

trust-sources[1].type=LOTL
trust-sources[1].verification-context=PID
trust-sources[1].location=https://trustedlist.serviceproviders.eudiw.dev/LOTL/01.xml
trust-sources[1].key-store.location=classpath:lotl.jks
trust-sources[1].key-store.type=JKS
trust-sources[1].service-types[0]=http://uri.etsi.org/Svc/Svctype/Provider/PID

time-to-live=P1D
