# Enables logging of Mongo mapping events
logging.level.org.springframework=INFO
logging.level.eu.europa.eu.esig=DEBUG
logging.level.org.springframework.boot.actuate.endpoint.web=DEBUG

management.endpoints.access.default=unrestricted
spring.web.error.include-stacktrace=ALWAYS
server.port=8080
spring.webflux.static-path-pattern=/public/**
spring.webflux.webjars-path-pattern=/webjars/**
spring.messages.basename=i18n/messages

# cors
cors.origins=*
cors.originPatterns=*
cors.methods=*
cors.headers=*
cors.credentials=false
cors.maxAge=3600

# Trust Sources
trustSources[0].type=KeyStore
trustSources[0].entity=PIDProvider
trustSources[0].service=Issuance
trustSources[0].keyStore.location=classpath:lotl.jks
trustSources[0].keyStore.type=JKS
trustSources[0].keyStore.password=
trustSources[1].type=LOTL
trustSources[1].entity=PIDProvider
trustSources[1].location=https://trustedlist.serviceproviders.eudiw.dev/LOTL/01.xml
trustSources[1].keyStore.location=classpath:lotl.jks
trustSources[1].keyStore.type=JKS
trustSources[1].keyStore.password=
trustSources[2].type=LOTE
trustSources[2].entity=PIDProvider
trustSources[2].location=https://acceptance.trust.tech.ec.europa.eu/lists/eudiw/pid-providers.json
trustSources[2].keyStore.location=classpath:lotl.jks
trustSources[2].keyStore.type=JKS
trustSources[2].keyStore.password=

#trustSources[0].lotl.serviceTypeFilter=PIDProvider
#trustSources[0].lotl.refreshInterval=0 0 * * * *
