# Enables logging of Mongo mapping events
logging.level.org.springframework=INFO
logging.level.eu.europa.eu.esig=DEBUG
logging.level.org.springframework.boot.actuate.endpoint.web=DEBUG

management.endpoints.access.default=unrestricted
spring.web.error.include-stacktrace=ALWAYS
server.port=8080
spring.webflux.static-path-pattern=/public/**
spring.webflux.webjars-path-pattern=/webjars/**
spring.messages.basename=i18n/messages

# cors
cors.origins=*
cors.originPatterns=*
cors.methods=*
cors.headers=*
cors.credentials=false
cors.maxAge=3600

# DSS
#trust-validator.dss.cache-location=dss-cache

# Wallet Providers
# LoTL
#trust-validator.trust-sources.wallet-providers.lotl.location=https://trustedlist.serviceproviders.eudiw.dev/LOTL/01.xml
#trust-validator.trust-sources.wallet-providers.lotl.signature-verification.location=classpath:lotl.jks
#trust-validator.trust-sources.wallet-providers.lotl.signature-verification.key-store-type=JKS
#trust-validator.trust-sources.wallet-providers.lotl.signature-verification.password=
#trust-validator.trust-sources.wallet-providers.lotl.issuance-service=http://uri.etsi.org/Svc/Svctype/Provider/Wallet
#trust-validator.trust-sources.wallet-providers.lotl.revocation-service=http://uri.etsi.org/Svc/Svctype/Provider/Wallet
# LoTE
#trust-validator.trust-sources.wallet-providers.lote.location=https://acceptance.trust.tech.ec.europa.eu/lists/eudiw/wallet-providers.json
#trust-validator.trust-sources.wallet-providers.lote.issuance-service=http://uri.etsi.org/19602/SvcType/WalletSolution/Issuance
#trust-validator.trust-sources.wallet-providers.lote.revocation-service=http://uri.etsi.org/19602/SvcType/WalletSolution/Revocation

# PID Providers
# LoTL
#trust-validator.trust-sources.pid-providers.lotl.location=https://trustedlist.serviceproviders.eudiw.dev/LOTL/01.xml
#trust-validator.trust-sources.pid-providers.lotl.signature-verification.location=classpath:lotl.jks
#trust-validator.trust-sources.pid-providers.lotl.signature-verification.key-store-type=JKS
#trust-validator.trust-sources.pid-providers.lotl.signature-verification.password=
#trust-validator.trust-sources.pid-providers.lotl.issuance-service=http://uri.etsi.org/Svc/Svctype/Provider/PID
#trust-validator.trust-sources.pid-providers.lotl.revocation-service=http://uri.etsi.org/Svc/Svctype/Provider/PID
# LoTE
#trust-validator.trust-sources.pid-providers.lote.location=https://acceptance.trust.tech.ec.europa.eu/lists/eudiw/pid-providers.json
#trust-validator.trust-sources.pid-providers.lote.issuance-service=http://uri.etsi.org/19602/SvcType/PID/Issuance
#trust-validator.trust-sources.pid-providers.lote.revocation-service=http://uri.etsi.org/19602/SvcType/PID/Revocation

# QEAA Providers
# LoTL
#trust-validator.trust-sources.qeaa-providers.lotl.location=https://trustedlist.serviceproviders.eudiw.dev/LOTL/01.xml
#trust-validator.trust-sources.qeaa-providers.lotl.signature-verification.location=classpath:lotl.jks
#trust-validator.trust-sources.qeaa-providers.lotl.signature-verification.key-store-type=JKS
#trust-validator.trust-sources.qeaa-providers.lotl.signature-verification.password=
#trust-validator.trust-sources.qeaa-providers.lotl.issuance-service=http://uri.etsi.org/TrstSvc/Svctype/EAA/Q
#trust-validator.trust-sources.qeaa-providers.lotl.revocation-service=http://uri.etsi.org/TrstSvc/Svctype/EAA/Q
# LoTE
#trust-validator.trust-sources.qeaa-providers.lote.location=https://acceptance.trust.tech.ec.europa.eu/lists/eudiw/pid-providers.json
#trust-validator.trust-sources.qeaa-providers.lote.issuance-service=http://uri.etsi.org/19602/SvcType/QEAA/Issuance
#trust-validator.trust-sources.qeaa-providers.lote.revocation-service=http://uri.etsi.org/19602/SvcType/QEAA/Revocation

# PubEAA Providers
# LoTL
#trust-validator.trust-sources.pub-eaa-providers.lotl.location=https://trustedlist.serviceproviders.eudiw.dev/LOTL/01.xml
#trust-validator.trust-sources.pub-eaa-providers.lotl.signature-verification.location=classpath:lotl.jks
#trust-validator.trust-sources.pub-eaa-providers.lotl.signature-verification.key-store-type=JKS
#trust-validator.trust-sources.pub-eaa-providers.lotl.signature-verification.password=
#trust-validator.trust-sources.pub-eaa-providers.lotl.issuance-service=http://uri.etsi.org/TrstSvc/Svctype/EAA/Pub-EAA
#trust-validator.trust-sources.pub-eaa-providers.lotl.revocation-service=http://uri.etsi.org/TrstSvc/Svctype/EAA/Pub-EAA
# LoTE
#trust-validator.trust-sources.pub-eaa-providers.lote.location=https://acceptance.trust.tech.ec.europa.eu/lists/eudiw/pid-providers.json
#trust-validator.trust-sources.pub-eaa-providers.lote.issuance-service=http://uri.etsi.org/19602/SvcType/PubEAA/Issuance
#trust-validator.trust-sources.pub-eaa-providers.lote.revocation-service=http://uri.etsi.org/19602/SvcType/PubEAA/Revocation

# mDL Providers
#trust-validator.trust-sources.eaa-providers[0].use-case=mDL
# LoTL
#trust-validator.trust-sources.eaa-providers[0].lotl.location=https://trustedlist.serviceproviders.eudiw.dev/LOTL/01.xml
#trust-validator.trust-sources.eaa-providers[0].lotl.signature-verification.location=classpath:lotl.jks
#trust-validator.trust-sources.eaa-providers[0].lotl.signature-verification.key-store-type=JKS
#trust-validator.trust-sources.eaa-providers[0].lotl.signature-verification.password=
#trust-validator.trust-sources.eaa-providers[0].lotl.issuance-service=http://uri.etsi.org/TrstSvc/Svctype/EAA
#trust-validator.trust-sources.eaa-providers[0].lotl.revocation-service=http://uri.etsi.org/TrstSvc/Svctype/EAA
# LoTE
#trust-validator.trust-sources.eaa-providers[0].lote.location=https://acceptance.trust.tech.ec.europa.eu/lists/eudiw/mdl-providers.json
#trust-validator.trust-sources.eaa-providers[0].lote.issuance-service=http://trust.ec.europa.eu/lists/mDL/SvcType/Issuance
#trust-validator.trust-sources.eaa-providers[0].lote.revocation-service=http://trust.ec.europa.eu/lists/mDL/SvcType/Revocation

# Wallet Relying Party Access Certificate Providers
# LoTL
#trust-validator.trust-sources.wrpac-providers.lotl.location=https://trustedlist.serviceproviders.eudiw.dev/LOTL/01.xml
#trust-validator.trust-sources.wrpac-providers.lotl.signature-verification.location=classpath:lotl.jks
#trust-validator.trust-sources.wrpac-providers.lotl.signature-verification.key-store-type=JKS
#trust-validator.trust-sources.wrpac-providers.lotl.signature-verification.password=
#trust-validator.trust-sources.wrpac-providers.lotl.issuance-service=http://uri.etsi.org/Svc/Svctype/CA/RPaccess
#trust-validator.trust-sources.wrpac-providers.lotl.revocation-service=http://uri.etsi.org/Svc/Svctype/CA/RPaccess
# LoTE
#trust-validator.trust-sources.wrpac-providers.lote.location=https://acceptance.trust.tech.ec.europa.eu/lists/eudiw/wrpac-providers.json
#trust-validator.trust-sources.wrpac-providers.lote.issuance-service=http://uri.etsi.org/19602/SvcType/WRPAC/Issuance
#trust-validator.trust-sources.wrpac-providers.lote.revocation-service=http://uri.etsi.org/19602/SvcType/WRPAC/Revocation

# Wallet Relying Party Registration Certificate Providers
# LoTL
#trust-validator.trust-sources.wrprc-providers.lotl.location=https://trustedlist.serviceproviders.eudiw.dev/LOTL/01.xml
#trust-validator.trust-sources.wrprc-providers.lotl.signature-verification.location=classpath:lotl.jks
#trust-validator.trust-sources.wrprc-providers.lotl.signature-verification.key-store-type=JKS
#trust-validator.trust-sources.wrprc-providers.lotl.signature-verification.password=
#trust-validator.trust-sources.wrprc-providers.lotl.issuance-service=http://uri.etsi.org/Svc/Svctype/CA/RPregistration
#trust-validator.trust-sources.wrprc-providers.lotl.revocation-service=http://uri.etsi.org/Svc/Svctype/CA/RPregistration
# LoTE
#trust-validator.trust-sources.wrprc-providers.lote.location=https://acceptance.trust.tech.ec.europa.eu/lists/eudiw/wrpac-providers.json
#trust-validator.trust-sources.wrprc-providers.lote.issuance-service=http://uri.etsi.org/19602/SvcType/WRPRC/Issuance
#trust-validator.trust-sources.wrprc-providers.lote.revocation-service=http://uri.etsi.org/19602/SvcType/WRPRC/Revocation

# KeyStore
#trust-validator.trust-sources.key-store.location=classpath:lotl.jks
#trust-validator.trust-sources.key-store.key-store-type=JKS
#trust-validator.trust-sources.key-store.password=
